# Custom resource CF template
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Custom resources for AWS CloudFormation

Parameters:
  architecture:
    Type: String
    Default: arm64
    AllowedValues:
      - arm64
      - x86_64
    Description: Compute architecture, e.g. arm64
  pythonVersion:
    Type: String
    Default: python3.9
    Description: Python version, e.g. python3.9

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: !Ref pythonVersion
    Architectures:
      - !Ref architecture

Resources:
  CustomResourceHelperLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: custom-resource-helper
      Description: Custom Resource Helper for Python
      ContentUri: "./lambda-layer/custom_resource_helper"
      CompatibleRuntimes:
        - !Ref pythonVersion
      CompatibleArchitectures:
        - !Ref architecture
    Metadata:
      BuildMethod: !Ref pythonVersion

  EchoUtilityFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: echo-utility
      Description: Echo utility, used to declare variables
      Handler: index.handler
      CodeUri: "./lambda/echo_utility"
      Layers:
        - !Ref CustomResourceHelperLayer
      Policies:
        - AWSLambdaExecute

Outputs:
  EchoUtilityFunctionArn:
    Description: "ARN for the EchoUtilityFunction custom resource function"
    Value: !GetAtt EchoUtilityFunction.Arn
