# CF template
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Mappings example application

Parameters:
  environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod
    Description: Deployment environment

Mappings:
  # Mapping "suffix"
  SuffixMap:
    dev:
      exampleFunctionName: mappings-example-dev
    test:
      exampleFunctionName: mappings-example-test
    prod:
      exampleFunctionName: mappings-example

Resources:
  MappingsExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Usage of "suffix"
      FunctionName:
        !FindInMap [SuffixMap, !Ref environment, exampleFunctionName]
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
          print("Hello mappings!")
      Runtime: python3.9
      Architectures:
        - arm64
      Policies:
        - AWSLambdaExecute
