# CF template
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Parameters example application

Parameters:
  # Constant "suffix"
  suffix:
    Type: String
    Default: dev
    Description: Resource name suffix, e.g. dev
  # Constant "pythonVersion"
  pythonVersion:
    Type: String
    Default: python3.9
    Description: Python version, e.g. python3.9

Resources:
  ParametersExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      # Usage of "suffix"
      FunctionName: !Sub "parameters-example-${suffix}"
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
          print("Hello parameters!")
      # Usage of "pythonVersion"
      Runtime: !Ref pythonVersion
      Architectures:
        - arm64
      Policies:
        - AWSLambdaExecute
