# Child CF template
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Sub-stacks example child application

Parameters:
  # Variable "powertoolsLayerArn"
  powertoolsLayerArn:
    Type: String
    Description: Powertools layer Arn

Resources:
  SubStackExampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sub-stack-example
      Handler: index.handler
      InlineCode: |
        from aws_lambda_powertools import Logger
        logger = Logger()
        def handler(event, context):
          logger.info("Hello sub-stack!")
      Runtime: python3.9
      Architectures:
        - arm64
      # Usage of "powertoolsLayerArn"
      Layers:
        - !Ref powertoolsLayerArn
      Policies:
        - AWSLambdaExecute
