# Parent CF template
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Sub-stacks example parent application

Parameters:
  powertoolsNameVersion:
    Type: String
    Default: AWSLambdaPowertoolsPythonV2-Arm64:73
    Description: Powertools name and version, e.g. AWSLambdaPowertoolsPythonV2-Arm64:71

Resources:
  ApplicationSubStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        # Variable "powertoolsLayerArn"
        powertoolsLayerArn: !Sub "arn:aws:lambda:${AWS::Region}:017000801446:layer:${powertoolsNameVersion}"
      TemplateURL: "./sub-stacks-child.yml"
