AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: AWS Cloudformation variables using parameters, mappings, sub-stacks or Custom Resources.

Parameters:
  environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - test
      - prod
    Description: Deployment environment, e.g. dev for development

Resources:
  ParametersStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./parameters.yml"
      TimeoutInMinutes: 10

  MappingsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./mappings.yml"
      TimeoutInMinutes: 10

  SubStacksStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./sub-stacks-parent.yml"
      TimeoutInMinutes: 10

  CustomResourcesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./custom-resources.yml"
      TimeoutInMinutes: 10

  CustomResourceVariablesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./custom-resource-variables.yml"
      TimeoutInMinutes: 10
      Parameters:
        echoUtilityFunctionArn: !GetAtt CustomResourcesStack.Outputs.EchoUtilityFunctionArn
